on:
  push:
    branches:
      - main

jobs:
  bump-changelog:
    runs-on: ubuntu-latest
    steps:
    - name: Accept all SDK licenses
      run: yes | /usr/local/lib/android/sdk/tools/bin/sdkmanager --licenses
