name: Warn on PRs to main branch

on:
  pull_request:
    types:
      - opened
      - reopened
    branches:
      - main

permissions:
  pull-requests: write

jobs:
  check-pr-base:
    runs-on: ubuntu-latest
    steps:
      - name: Validate PR head and base branches
        if: "${{ github.base_ref == 'main' && github.head_ref != 'staging' }}"
        uses: actions/github-script@d556feaca394842dc55e4734bf3bb9f685482fa0 # v6.3.3
        id: validate-pr-base
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const script = require('.github/check-pr-base.js')
            await script({github, context})
