name: Warn on PRs to main branch

on:
  pull_request:
    types:
      - opened
      - reopened
    branches:
      - main

permissions:
  pull-requests: write

jobs:
  check-pr-base:
    runs-on: ubuntu-latest
    steps:
      - name: Validate PR head and base branches
        if: "${{ github.base_ref == 'main' && github.head_ref != 'staging' }}"
        uses: actions/github-script@d556feaca394842dc55e4734bf3bb9f685482fa0 # v6.3.3
        with:
          script: |
            github.rest.issues.createComment({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              issue_number: context.payload.number,
              body: `## :warning: Warning :warning:\nThis PR is targeting the main branch but did not originate from staging, please make sure this is intentional`,
            });
