on:
  push:
    branches:
      - main

jobs:
  one:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

    - shell: bash
      run: echo $ANDROID_HOME
