on:
  pull_request:
  workflow_dispatch:
    inputs:
      inAppUpdatePriority:
        description: 'In app update priority (0-5)'
        type: number
        default: "0"
        required: false

jobs:
  one:
    runs-on: ubuntu-latest
    steps:

    - shell: bash
      run: echo $DOODOO
      env:
        DOODOO: ${{ inputs.inAppUpdatePriority ?? '0' }}
